# Generated by Django 4.2 on 2023-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tengri', '0003_rename_htmlurl_post_html_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgUrl',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='watches',
            field=models.IntegerField(default=0),
        ),
    ]
